print("\"RAHUL\".replace(\"UL\",\"UR\",1)","=","RAHUL".replace("UL","UR",1))
print("\"srahuls\".rfind(\"s\",0,len(\"srahuls\"))","=","srahuls".rfind("s",0,len("srahuls")))
print("\"srahuls\".rindex(\"l\",0,len(\"srahuls\"))","=","srahuls".rindex("l",0,len("srahuls")))
print("\"RAHUL\".rjust(10,\"0\")","=","RAHUL".rjust(10,"0"))
print("\"RAHUL888888\".rstrip(\"8\")","=","RAHUL888888".rstrip("8"))
